version: '2'

networks:
  bcnet:
    name: order-mgmt_bcnet

services:

  order-mgmt-node-api-org1:
    container_name: order-mgmt-node-api-org1
    image: order-mgmt-node-api:amd64-v1.0.0
    build: ./src
    restart: always
    environment:
      - TZ=Asia/Taipei
      - NODE_API_PORT=5008
      - GATEWAY_FILE_PATH=/src/gateway/org1-Network.yaml
      - WALLET_PATH=/src/wallet
    working_dir: /src/order-mgmt-node-api
    command: ["pm2-docker", "process.yml", "--only", "order-mgmt-node-api"]
    volumes:
      - ./wallet:/src/wallet
      - ./gateway:/src/gateway
      - /home/judy/go/src/github.com/hyperledger/order-mgmt/order-mgmt-network/organizations:/src/organizations
    ports:
      - 5008:5008
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    networks:
      - bcnet

  order-mgmt-node-api-org2:
    container_name: order-mgmt-node-api-org2
    image: order-mgmt-node-api:amd64-v1.0.0
    build: ./src
    restart: always
    environment:
      - TZ=Asia/Taipei
      - NODE_API_PORT=5009
      - GATEWAY_FILE_PATH=/src/gateway/org2-Network.yaml
      - WALLET_PATH=/src/wallet
    working_dir: /src/order-mgmt-node-api
    command: ["pm2-docker", "process.yml", "--only", "order-mgmt-node-api"]
    volumes:
      - ./wallet:/src/wallet
      - ./gateway:/src/gateway
      - /home/judy/go/src/github.com/hyperledger/order-mgmt/order-mgmt-network/organizations:/src/organizations
    ports:
      - 5009:5009
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    networks:
      - bcnet

